aws_dbt_snowflake_project:
  outputs:
    dev:
      account: YHQLIKI-NK44850
      database: AIRBNB
      password: **************
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: RAMANBARNWAL81
      warehouse: COMPUTE_WH
  target: dev
